<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>csv</string>
	</array>
	<key>name</key>
	<string>csv syntax</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>support</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>markup.bold</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>invalid</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?:(?:"(?:[^"]*"")*[^"]*",?)|(?:[^,]*,?))((?:"(?:[^"]*"")*[^"]*",?)|(?:[^,]*,?))?((?:"(?:[^"]*"")*[^"]*",?)|(?:[^,]*,?))?((?:"(?:[^"]*"")*[^"]*",?)|(?:[^,]*,?))?((?:"(?:[^"]*"")*[^"]*",?)|(?:[^,]*,?))?((?:"(?:[^"]*"")*[^"]*",?)|(?:[^,]*,?))?((?:"(?:[^"]*"")*[^"]*",?)|(?:[^,]*,?))?((?:"(?:[^"]*"")*[^"]*",?)|(?:[^,]*,?))?((?:"(?:[^"]*"")*[^"]*",?)|(?:[^,]*,?))?((?:"(?:[^"]*"")*[^"]*",?)|(?:[^,]*,?))?</string>
			<key>name</key>
			<string>rainbow.first</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.csv</string>
	<key>uuid</key>
	<string>ca03e352-04ef-4340-9a6b-9b99aae1c418</string>
</dict>
</plist>
